<script src="{{asset('./front-end/js/jquery.min.js')}}"></script>
<script src="{{asset('./front-end/js/jquery-migrate-3.0.1.min.js')}}"></script>
<script src="{{asset('./front-end/js/popper.min.js')}}"></script>
<script src="{{asset('./front-end/js/bootstrap.min.js')}}"></script>
<script src="{{asset('./front-end/js/jquery.easing.1.3.js')}}"></script>
<script src="{{asset('./front-end/js/jquery.waypoints.min.js')}}"></script>
<script src="{{asset('./front-end/js/jquery.stellar.min.js')}}"></script>
<script src="{{asset('./front-end/js/owl.carousel.min.js')}}"></script>
<script src="{{asset('./front-end/js/jquery.magnific-popup.min.js')}}"></script>
<script src="{{asset('./front-end/js/aos.js')}}"></script>
<script src="{{asset('./front-end/js/jquery.animateNumber.min.js')}}"></script>
<script src="{{asset('./front-end/js/bootstrap-datepicker.js')}}"></script>
<script src="{{asset('./front-end/js/jquery.timepicker.min.js')}}"></script>
<script src="{{asset('./front-end/js/scrollax.min.js')}}"></script>
<!-- <script src="{{asset('./front-end/js/google-map.js')}}"></script> -->
<script src="{{asset('./front-end/js/main.js')}}"></script>